name: ccp_rip
description: A Dart library to calculate CCP keys, RIP, and AlgÃ©rie Poste fees
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
